name: Build & Test

on:
  push:
    branches:
      - 'dotnet-sts'
      - 'dotnet-lts'
    paths:
      - 'solution/**'
      - '!solution/examples/**'
  pull_request:
    branches:
      - 'dotnet-sts'
      - 'dotnet-lts'
    paths:
      - 'solution/**'
      - '!solution/examples/**'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DOTNET_NOLOGO: true
      DOTNET_CLI_TELEMETRY_OPTOUT: true
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version:  |
            8.0.x
      - name: Restore
        run: dotnet restore confluent-kafka-factory-extension.sln --verbosity minimal --force
        working-directory: solution
      - name: Build
        run: dotnet build confluent-kafka-factory-extension.sln --configuration Release --no-restore --verbosity minimal
        working-directory: solution
      - name: Test
        run: dotnet test confluent-kafka-factory-extension.sln --configuration Release --no-build --verbosity minimal
        working-directory: solution
