name: .NET Core

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.x'
    - name: Install dependencies
      run: dotnet restore Confluent.Kafka.FactoryExtension.sln
    - name: Build
      run: dotnet build Confluent.Kafka.FactoryExtension.sln --configuration Release --no-restore      
    - name: Test
      run: dotnet test Confluent.Kafka.FactoryExtension.sln --configuration Release --no-restore --verbosity normal
