name: Publish to NuGet & GitHub

on:
  release:
    types: [ published ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DOTNET_NOLOGO: true
      DOTNET_CLI_TELEMETRY_OPTOUT: true
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core 3.1.x
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '3.1.x'
      - name: Setup .NET Core 5.0.x
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.0.x'
      - name: Restore
        run: dotnet restore Confluent.Kafka.FactoryExtension.sln --verbosity minimal --force
      - name: Build
        run: dotnet build Confluent.Kafka.FactoryExtension.sln --configuration Release --no-restore --verbosity minimal
      - name: Pack
        run: dotnet pack Confluent.Kafka.FactoryExtension.csproj --configuration Release --no-build --verbosity minimal -v n /p:PackageVersion=${{ github.event.release.tag_name }} /p:PackageReleaseNotes="See https://github.com/labuscpi/confluent-kafka-factory-extension/releases/tag/${{ github.event.release.tag_name }}"
        working-directory: src/Confluent.Kafka.FactoryExtension
      - name: Publish Package to nuget.org
        run: dotnet nuget push **/*.nupkg --api-key ${{ secrets.NUGETAPIKEY }} --source https://api.nuget.org/v3/index.json --no-symbols true --skip-duplicate
